### ISSUE TITLE
Unable to add Conversion configuration without error

### ISSUE THREAD

**Issue by csyvenky-finops** [finopsfoundation/focus_converters#126]
I have created _rename_column_ configurations for the following:

1. BillingCurrencyCode to BillingCurrency
2. ConsumedService to ServiceName
3. SubscriptionId to SubAccountId
4. SubscriptionName to SubAccountName

I am unwilling to submit them in a PR because as-is they don't pass the following test.

Running the following command:

`python -m focus_converter.main explain --provider azure`

Yields the following error:

`ValidationError: 1 validation error for ConversionPlan
focus_column
  Input should be 'ChargePeriodStart', 'ChargePeriodEnd', 'BillingPeriodStart', 'BillingPeriodEnd', 'Provider', 'Publisher', 'BillingAccountId', 'AmortisedCost', 'BilledCost',
'Region', 'ChargeType' or 'ServiceCategory' [type=enum, input_value='BillingCurrency', input_type=str]`

This error also reveals other issues, the following two fields aren't even associated with the [FOCUS Spec](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/tree/working_draft/specification/dimensions).

1. AmortisedCost
2. BilledCost

**Comment by varunmittal91** [comment]
Recreated PR and merged #132.
