### ISSUE TITLE
[proposed Bug] Unable to add Azure conversion rule to parse date

### ISSUE THREAD

**Issue by csyvenky-finops** [finopsfoundation/focus_converters#141]
I’ve added two conversion functions (_parse_datetime_, _assign_utc_timezone_), when I include them in the project structure and run the _convert_ function, I neither get an error or output of any kind, the app runs continually without stopping, until I interrupt the notebook runtime.

focus_converters/focus_converter_base/focus_converter/conversion_configs/azure/D002_S001.yaml
```
plan_name: parse mm/dd/YYYY from BillingPeriodStartDate
conversion_type: parse_datetime
column: BillingPeriodStartDate
focus_column: BillingPeriodStart
conversion_args: "%m/%d/%Y"
```

focus_converters/focus_converter_base/focus_converter/conversion_configs/azure/D002_S002.yaml
```
plan_name: convert BillingPeriodStartDate to BillingPeriodStart
conversion_type: assign_utc_timezone
column: BillingPeriodStartDate
focus_column: BillingPeriodStart
```

**Comment by varunmittal91** [comment]
@csyvenky-finops there is a problem in your D002_S002, file. Looks like the column should be BillingPeriodStart which you already parsed to datetime.

**Comment by csyvenky-finops** [comment]
That was it, great catch sir! Closing issue.
