### ISSUE TITLE
Plan graph image is too small / unreadable

### ISSUE THREAD

**Issue by sxdjt** [finopsfoundation/focus_converters#302]
**Is your feature request related to a problem? Please describe.**

1. When generating a plan graph, the resulting image is too small to be readable
2. The horizontal span of the plan is too wide for reasonable use.  A vertical layout would be more usable for documentation/presentations.

```
focus-converter explain --provider azure --image-path ~/Desktop/focus.png
```

**Describe the solution you'd like**

I would like to be able to specify the image dimensions and orientation.  E.g. ```--orientation vertical --width 2000``` .  This would generate the plan in a vertical layout with the branches going out horizontally, 2000 pixels wide.

**Describe alternatives you've considered**

Up-scaling the existing output does not produce clear/readable text.

**Comment by sxdjt** [comment]
Sure - current output attached.

![focus](https://github.com/finopsfoundation/focus_converters/assets/53812540/129837b8-cd6f-471f-a38a-ff14b0923362)

**Comment by varunmittal91** [comment]
Hi @sxdjt, did you try the new version. It produces left to right graph which can be scaled much better.

**Comment by sxdjt** [comment]
@varunmittal91 That is _much better_!  Thank you for the work.

![focus-1](https://github.com/finopsfoundation/focus_converters/assets/53812540/12ba30a1-4bae-4dd4-ad1d-fa75d7df68b6)
