### ISSUE TITLE
Publish Docker Image to a Container Registry

### ISSUE THREAD

**Issue by brianwyka** [finopsfoundation/focus_converters#312]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Publish the docker image packaging the `focus_converter` application.  It can be published to any registry, DockerHub, Github, etc...

**Describe alternatives you've considered**
N/A

**Additional context**
Recently a docker image was added to containerize the converter.  It would be nice to publish this docker image to a container registry such that it can be consumed by end users.

**Comment by brianwyka** [comment]
@varunmittal91 , in reference to the addition of the `Dockerfile` here:
https://github.com/finopsfoundation/focus_converters/pull/311

**Comment by varunmittal91** [comment]
Hi @brianwyka, I am working on sorting out the public part. I have a github action which is not producing right tags.
I wanted one tag to be the current version and the other one to latest.

Do you have experience with this, if so I would love to make some progress on this?

**Comment by brianwyka** [comment]
Hi @varunmittal91 , is this the action you are referring to?
https://github.com/finopsfoundation/focus_converters/blob/dev/.github/workflows/docker_build.yaml

**Comment by varunmittal91** [comment]
FOCUS docker image available at, https://hub.docker.com/r/finopsfoundation/focus-converter/tags
