### ISSUE TITLE
GCP conversion example

### ISSUE THREAD

**Issue by Maxlotl** [finopsfoundation/focus_converters#347]
**Is your feature request related to a problem? Please describe.**
I'm trying to find an example of how to convert GCP billing reports with focus and I failed to find any example. Can you please describe/create an example of the appropriate usage of focus-converter?

**Describe the solution you'd like**
Please add an required section to the CMD example

**Describe alternatives you've considered**
there is no alternatives to simple example :-)

**Additional context**
Thank you !

**Comment by mirusky** [comment]
Related #346

**Comment by Maxlotl** [comment]
@mirusky  I would like to assist you in your work. Do you have some task mngs like Jira where people can take task and help you with the code ?

**Comment by mirusky** [comment]
I'm not a direct contributor, I'm just assisting with the multiples files and providers since I've a lot of knowledge on it

**Comment by Maxlotl** [comment]
Thank you
