### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by brianwyka** [finopsfoundation/focus_converters#362]
Is there a plan to continue to maintain this repository anymore?  Or will be be decommissioned since cloud providers are now generating `FOCUS` reports.

**Comment by brianwyka** [comment]
cc @varunmittal91 .  Do you know?

**Comment by mike-finopsorg** [comment]
Hey @brianwyka, While low activity the plan is to continue to maintain this repository, however we will likely decommission the cloud provider rules we have today (in preference for the CSP provided datasets) and start looking into other datasets beyond the major cloud providers. I have a task in my queue to come back to this project and perform some tidy up, hoping to get to it over the next month.

**Comment by brianwyka** [comment]
Thanks @mike-finopsorg.  Microsoft has some nice documentation on the FinOps Toolkit website for conversion, however it's lacking for AWS / GCP.  Would be nice to have some updates since 1.0 and 1.1 have been released to cover the gaps for CSP conversion rules
