### ISSUE TITLE
Q: Is there a roadmap.

### ISSUE THREAD

**Issue by j-d-carmichael** [finopsfoundation/focus_converters#5]
I am working on a large project consuming multiple cloud provider's cost data in gigabytes, daily - the client is BMW.

We are now looking to see if we can normalise the naming between the providers, and of course, after some base research stumbled upon the FOCUS project.

I just requested access to the focus.finops community.

I would love to speak to anyone about this project and how we might integrate FOCUS into our project, or, potentially even contribute in some way.

Thanks,
John

**Comment by mike-finopsorg** [comment]
Yes we are working on building out the roadmap here https://github.com/orgs/finopsfoundation/projects/2/views/1 Watch this space over the next 2 weeks. :)

We will reach out about a sync with you regarding your project.
