### ISSUE TITLE
GCP-ResourceName

### ISSUE THREAD

**Issue by varunmittal91** [finopsfoundation/focus_converters#52]

**Comment by sgonuguntabox** [comment]
This will resource.name 

- Resource is a struct, we need to get the **name** key from resource.
- This is available only in detailed export https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables/detailed-usage#:~:text=generated%20relevant%20usage.-,resource.name,-String

**Comment by sgonuguntabox** [comment]
This works only for the certain services that are supported by GCP

**Comment by varunmittal91** [comment]
@sgonuguntabox I just pushed a PR would you have time to review it, https://github.com/finopsfoundation/focus_converters/pull/340.
